2015-12-11 16:18:54,262 export          INFO     Hi PACT Lab, this is faithful android Martin from Laura's server. Everything is alright here, and seems to be
     a good time for a hunt. I am going out for a regular check and will come back soon. Don't miss me PACT Lab, it wouldn't
     take too long.
2015-12-11 16:18:54,265 export          INFO      (Martin is out for hunting data......) 
2015-12-11 16:18:54,265 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export ......
2015-12-11 16:18:54,281 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:18:54,757 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export
Issues: None
2015-12-11 16:18:54,759 export          INFO     Alright I am back! Pretty fruitful. Seem like it is going to be comfortable for a little while. Alright,
     I am heading to the server for a little rest, will talk to you guys in PACT Lab in a little while. -- Martin
2015-12-11 16:18:54,759 export.safeExport INFO     Database update in progress......
2015-12-11 16:18:54,759 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxiety ......
2015-12-11 16:18:54,761 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:18:54,860 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxiety
Issues: None
2015-12-11 16:18:54,860 export.safeExport INFO     No new entries found in StateAnxiety
2015-12-11 16:18:54,860 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AUDIT ......
2015-12-11 16:18:54,863 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:18:54,930 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AUDIT
Issues: None
2015-12-11 16:18:54,931 export.safeExport INFO     No new entries found in AUDIT
2015-12-11 16:18:54,931 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MultiUserExperience ......
2015-12-11 16:18:54,934 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:18:55,003 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MultiUserExperience
Issues: None
2015-12-11 16:18:55,003 export.safeExport INFO     Questionnaire MultiUserExperience updated - 2 new entries received.
2015-12-11 16:18:55,005 export.createFile INFO     New data file created: active_data/MultiUserExperience_Dec_11_2015.csv
2015-12-11 16:18:55,005 export.safeWrite INFO     Writing new entries from MultiUserExperience to active_data/MultiUserExperience_Dec_11_2015.csv: writing in progress......
2015-12-11 16:18:55,020 export.safeKeep CRITICAL MultiUserExperience data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:18:57,697 export.safeWrite INFO     Questionnaire MultiUserExperience update finished - 2 new entries recoded successfully.
2015-12-11 16:18:57,698 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Vivid ......
2015-12-11 16:18:57,700 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:18:57,747 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Vivid
Issues: None
2015-12-11 16:18:57,748 export.safeExport INFO     No new entries found in Vivid
2015-12-11 16:18:57,749 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CC ......
2015-12-11 16:18:57,759 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:18:57,820 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CC
Issues: None
2015-12-11 16:18:57,821 export.safeExport INFO     Questionnaire CC updated - 17 new entries received.
2015-12-11 16:18:57,821 export.createFile INFO     New data file created: active_data/CC_Dec_11_2015.csv
2015-12-11 16:18:57,822 export.safeWrite INFO     Writing new entries from CC to active_data/CC_Dec_11_2015.csv: writing in progress......
2015-12-11 16:18:57,822 export.safeKeep CRITICAL CC data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:18:59,754 export.safeWrite INFO     Questionnaire CC update finished - 17 new entries recoded successfully.
2015-12-11 16:18:59,754 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/BBSIQ ......
2015-12-11 16:18:59,756 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:18:59,819 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/BBSIQ
Issues: None
2015-12-11 16:18:59,822 export.safeExport INFO     Questionnaire BBSIQ updated - 25 new entries received.
2015-12-11 16:18:59,822 export.createFile INFO     New data file created: active_data/BBSIQ_Dec_11_2015.csv
2015-12-11 16:18:59,823 export.safeWrite INFO     Writing new entries from BBSIQ to active_data/BBSIQ_Dec_11_2015.csv: writing in progress......
2015-12-11 16:18:59,823 export.safeKeep CRITICAL BBSIQ data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:01,329 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:01,334 export.safeWrite INFO     Questionnaire BBSIQ update finished - 25 new entries recoded successfully.
2015-12-11 16:19:01,335 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_DS ......
2015-12-11 16:19:01,336 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:01,368 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_DS
Issues: None
2015-12-11 16:19:01,369 export.safeExport INFO     Questionnaire DASS21_DS updated - 25 new entries received.
2015-12-11 16:19:01,369 export.createFile INFO     New data file created: active_data/DASS21_DS_Dec_11_2015.csv
2015-12-11 16:19:01,370 export.safeWrite INFO     Writing new entries from DASS21_DS to active_data/DASS21_DS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:01,370 export.safeKeep CRITICAL DASS21_DS data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:02,616 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:02,616 export.safeWrite INFO     Questionnaire DASS21_DS update finished - 25 new entries recoded successfully.
2015-12-11 16:19:02,616 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/QOL ......
2015-12-11 16:19:02,617 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:02,659 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/QOL
Issues: None
2015-12-11 16:19:02,661 export.safeExport INFO     Questionnaire QOL updated - 28 new entries received.
2015-12-11 16:19:02,662 export.createFile INFO     New data file created: active_data/QOL_Dec_11_2015.csv
2015-12-11 16:19:02,662 export.safeWrite INFO     Writing new entries from QOL to active_data/QOL_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:02,662 export.safeKeep CRITICAL QOL data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:04,410 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:04,411 export.safeWrite INFO     Questionnaire QOL update finished - 28 new entries recoded successfully.
2015-12-11 16:19:04,411 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/OA ......
2015-12-11 16:19:04,413 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:04,877 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/OA
Issues: None
2015-12-11 16:19:04,878 export.safeExport INFO     Questionnaire OA updated - 49 new entries received.
2015-12-11 16:19:04,879 export.createFile INFO     New data file created: active_data/OA_Dec_11_2015.csv
2015-12-11 16:19:04,879 export.safeWrite INFO     Writing new entries from OA to active_data/OA_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:04,880 export.safeKeep CRITICAL OA data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:06,261 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:06,261 export.safeWrite INFO     Questionnaire OA update finished - 49 new entries recoded successfully.
2015-12-11 16:19:06,262 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/RR ......
2015-12-11 16:19:06,263 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:06,326 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/RR
Issues: None
2015-12-11 16:19:06,328 export.safeExport INFO     Questionnaire RR updated - 25 new entries received.
2015-12-11 16:19:06,328 export.createFile INFO     New data file created: active_data/RR_Dec_11_2015.csv
2015-12-11 16:19:06,328 export.safeWrite INFO     Writing new entries from RR to active_data/RR_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:06,329 export.safeKeep CRITICAL RR data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:08,241 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:08,242 export.safeWrite INFO     Questionnaire RR update finished - 25 new entries recoded successfully.
2015-12-11 16:19:08,242 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImpactAnxiousImagery ......
2015-12-11 16:19:08,244 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:08,304 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImpactAnxiousImagery
Issues: None
2015-12-11 16:19:08,305 export.safeExport INFO     Questionnaire ImpactAnxiousImagery updated - 36 new entries received.
2015-12-11 16:19:08,305 export.createFile INFO     New data file created: active_data/ImpactAnxiousImagery_Dec_11_2015.csv
2015-12-11 16:19:08,306 export.safeWrite INFO     Writing new entries from ImpactAnxiousImagery to active_data/ImpactAnxiousImagery_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:08,306 export.safeKeep CRITICAL ImpactAnxiousImagery data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:09,606 export.safeWrite INFO     Questionnaire ImpactAnxiousImagery update finished - 36 new entries recoded successfully.
2015-12-11 16:19:09,606 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/SUDS ......
2015-12-11 16:19:09,608 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:09,650 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/SUDS
Issues: None
2015-12-11 16:19:09,651 export.safeExport INFO     Questionnaire SUDS updated - 43 new entries received.
2015-12-11 16:19:09,651 export.createFile INFO     New data file created: active_data/SUDS_Dec_11_2015.csv
2015-12-11 16:19:09,652 export.safeWrite INFO     Writing new entries from SUDS to active_data/SUDS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:09,652 export.safeKeep CRITICAL SUDS data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:10,933 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:10,934 export.safeWrite INFO     Questionnaire SUDS update finished - 43 new entries recoded successfully.
2015-12-11 16:19:10,934 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/PilotUserExperience ......
2015-12-11 16:19:10,936 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:10,992 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/PilotUserExperience
Issues: None
2015-12-11 16:19:10,992 export.safeExport INFO     No new entries found in PilotUserExperience
2015-12-11 16:19:10,992 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReRu ......
2015-12-11 16:19:10,995 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:11,116 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReRu
Issues: None
2015-12-11 16:19:11,116 export.safeExport INFO     No new entries found in ReRu
2015-12-11 16:19:11,117 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AnxietyTriggers ......
2015-12-11 16:19:11,118 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:11,165 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AnxietyTriggers
Issues: None
2015-12-11 16:19:11,166 export.safeExport INFO     Questionnaire AnxietyTriggers updated - 21 new entries received.
2015-12-11 16:19:11,167 export.createFile INFO     New data file created: active_data/AnxietyTriggers_Dec_11_2015.csv
2015-12-11 16:19:11,167 export.safeWrite INFO     Writing new entries from AnxietyTriggers to active_data/AnxietyTriggers_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:11,167 export.safeKeep CRITICAL AnxietyTriggers data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:12,781 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:12,782 export.safeWrite INFO     Questionnaire AnxietyTriggers update finished - 21 new entries recoded successfully.
2015-12-11 16:19:12,783 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD ......
2015-12-11 16:19:12,784 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:12,843 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD
Issues: None
2015-12-11 16:19:12,844 export.safeExport INFO     Questionnaire DD updated - 21 new entries received.
2015-12-11 16:19:12,845 export.createFile INFO     New data file created: active_data/DD_Dec_11_2015.csv
2015-12-11 16:19:12,845 export.safeWrite INFO     Writing new entries from DD to active_data/DD_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:12,845 export.safeKeep CRITICAL DD data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:14,123 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:14,125 export.safeWrite INFO     Questionnaire DD update finished - 21 new entries recoded successfully.
2015-12-11 16:19:14,125 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/FollowUp_ChangeInTreatment ......
2015-12-11 16:19:14,126 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:14,161 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/FollowUp_ChangeInTreatment
Issues: None
2015-12-11 16:19:14,161 export.safeExport INFO     No new entries found in FollowUp_ChangeInTreatment
2015-12-11 16:19:14,161 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Credibility ......
2015-12-11 16:19:14,164 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:14,199 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Credibility
Issues: None
2015-12-11 16:19:14,200 export.safeExport INFO     Questionnaire Credibility updated - 21 new entries received.
2015-12-11 16:19:14,200 export.createFile INFO     New data file created: active_data/Credibility_Dec_11_2015.csv
2015-12-11 16:19:14,201 export.safeWrite INFO     Writing new entries from Credibility to active_data/Credibility_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:14,201 export.safeKeep CRITICAL Credibility data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:15,940 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:15,941 export.safeWrite INFO     Questionnaire Credibility update finished - 21 new entries recoded successfully.
2015-12-11 16:19:15,941 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MentalHealthHxTx ......
2015-12-11 16:19:15,942 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:16,027 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MentalHealthHxTx
Issues: None
2015-12-11 16:19:16,028 export.safeExport INFO     Questionnaire MentalHealthHxTx updated - 24 new entries received.
2015-12-11 16:19:16,029 export.createFile INFO     New data file created: active_data/MentalHealthHxTx_Dec_11_2015.csv
2015-12-11 16:19:16,029 export.safeWrite INFO     Writing new entries from MentalHealthHxTx to active_data/MentalHealthHxTx_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:16,030 export.safeKeep CRITICAL MentalHealthHxTx data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:17,830 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:17,832 export.safeWrite INFO     Questionnaire MentalHealthHxTx update finished - 24 new entries recoded successfully.
2015-12-11 16:19:17,832 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImageryPrime ......
2015-12-11 16:19:17,833 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:17,879 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImageryPrime
Issues: None
2015-12-11 16:19:17,880 export.safeExport INFO     Questionnaire ImageryPrime updated - 36 new entries received.
2015-12-11 16:19:17,881 export.createFile INFO     New data file created: active_data/ImageryPrime_Dec_11_2015.csv
2015-12-11 16:19:17,881 export.safeWrite INFO     Writing new entries from ImageryPrime to active_data/ImageryPrime_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:17,883 export.safeKeep CRITICAL ImageryPrime data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:19,636 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:19,637 export.safeWrite INFO     Questionnaire ImageryPrime update finished - 36 new entries recoded successfully.
2015-12-11 16:19:19,637 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReasonsForEnding ......
2015-12-11 16:19:19,639 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:19,688 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReasonsForEnding
Issues: None
2015-12-11 16:19:19,690 export.safeExport INFO     Questionnaire ReasonsForEnding updated - 3 new entries received.
2015-12-11 16:19:19,690 export.createFile INFO     New data file created: active_data/ReasonsForEnding_Dec_11_2015.csv
2015-12-11 16:19:19,691 export.safeWrite INFO     Writing new entries from ReasonsForEnding to active_data/ReasonsForEnding_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:19,691 export.safeKeep CRITICAL ReasonsForEnding data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:20,976 export.safeWrite INFO     Questionnaire ReasonsForEnding update finished - 3 new entries recoded successfully.
2015-12-11 16:19:20,976 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxietyPost ......
2015-12-11 16:19:20,977 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:21,013 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxietyPost
Issues: None
2015-12-11 16:19:21,013 export.safeExport INFO     No new entries found in StateAnxietyPost
2015-12-11 16:19:21,013 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Demographic ......
2015-12-11 16:19:21,018 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:21,070 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Demographic
Issues: None
2015-12-11 16:19:21,071 export.safeExport INFO     Questionnaire Demographic updated - 21 new entries received.
2015-12-11 16:19:21,072 export.createFile INFO     New data file created: active_data/Demographic_Dec_11_2015.csv
2015-12-11 16:19:21,072 export.safeWrite INFO     Writing new entries from Demographic to active_data/Demographic_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:21,072 export.safeKeep CRITICAL Demographic data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:22,416 export.safeWrite INFO     Questionnaire Demographic update finished - 21 new entries recoded successfully.
2015-12-11 16:19:22,416 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CIHS ......
2015-12-11 16:19:22,417 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:22,458 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CIHS
Issues: None
2015-12-11 16:19:22,458 export.safeExport INFO     Questionnaire CIHS updated - 2 new entries received.
2015-12-11 16:19:22,459 export.createFile INFO     New data file created: active_data/CIHS_Dec_11_2015.csv
2015-12-11 16:19:22,459 export.safeWrite INFO     Writing new entries from CIHS to active_data/CIHS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:22,459 export.safeKeep CRITICAL CIHS data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:24,111 export.safeWrite INFO     Questionnaire CIHS update finished - 2 new entries recoded successfully.
2015-12-11 16:19:24,111 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_AS ......
2015-12-11 16:19:24,113 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:24,222 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_AS
Issues: None
2015-12-11 16:19:24,223 export.safeExport INFO     Questionnaire DASS21_AS updated - 21 new entries received.
2015-12-11 16:19:24,223 export.createFile INFO     New data file created: active_data/DASS21_AS_Dec_11_2015.csv
2015-12-11 16:19:24,223 export.safeWrite INFO     Writing new entries from DASS21_AS to active_data/DASS21_AS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:24,223 export.safeKeep CRITICAL DASS21_AS data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:25,578 export.safeWrite INFO     Questionnaire DASS21_AS update finished - 21 new entries recoded successfully.
2015-12-11 16:19:25,579 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD_FU ......
2015-12-11 16:19:25,580 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:19:25,611 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD_FU
Issues: None
2015-12-11 16:19:25,611 export.safeExport INFO     Questionnaire DD_FU updated - 5 new entries received.
2015-12-11 16:19:25,612 export.createFile INFO     New data file created: active_data/DD_FU_Dec_11_2015.csv
2015-12-11 16:19:25,612 export.safeWrite INFO     Writing new entries from DD_FU to active_data/DD_FU_Dec_11_2015.csv: writing in progress......
2015-12-11 16:19:25,612 export.safeKeep CRITICAL DD_FU data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:27,293 export.safeWrite INFO     Questionnaire DD_FU update finished - 5 new entries recoded successfully.
2015-12-11 16:19:27,294 export.safeExport INFO     Database update finished: 19 questionnaires' data updated.
2015-12-11 16:20:40,390 export          INFO     Hi PACT Lab, this is faithful android Martin from Laura's server. Everything is alright here, and seems to be
     a good time for a hunt. I am going out for a regular check and will come back soon. Don't miss me PACT Lab, it wouldn't
     take too long.
2015-12-11 16:20:40,390 export          INFO      (Martin is out for hunting data......) 
2015-12-11 16:20:40,390 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export ......
2015-12-11 16:20:40,402 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:40,487 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export
Issues: None
2015-12-11 16:20:40,488 export          INFO     Alright I am back! Pretty fruitful. Seem like it is going to be comfortable for a little while. Alright,
     I am heading to the server for a little rest, will talk to you guys in PACT Lab in a little while. -- Martin
2015-12-11 16:20:40,488 export.safeExport INFO     Database update in progress......
2015-12-11 16:20:40,488 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxiety ......
2015-12-11 16:20:40,490 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:40,539 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxiety
Issues: None
2015-12-11 16:20:40,539 export.safeExport INFO     No new entries found in StateAnxiety
2015-12-11 16:20:40,540 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AUDIT ......
2015-12-11 16:20:40,541 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:40,583 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AUDIT
Issues: None
2015-12-11 16:20:40,584 export.safeExport INFO     No new entries found in AUDIT
2015-12-11 16:20:40,584 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MultiUserExperience ......
2015-12-11 16:20:40,587 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:40,621 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MultiUserExperience
Issues: None
2015-12-11 16:20:40,622 export.safeExport INFO     Questionnaire MultiUserExperience updated - 2 new entries received.
2015-12-11 16:20:40,622 export.safeWrite INFO     Writing new entries from MultiUserExperience to active_data/MultiUserExperience_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:40,645 export.safeWrite INFO     Questionnaire MultiUserExperience update finished - 2 new entries recoded successfully.
2015-12-11 16:20:40,648 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Vivid ......
2015-12-11 16:20:40,654 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:40,704 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Vivid
Issues: None
2015-12-11 16:20:40,704 export.safeExport INFO     No new entries found in Vivid
2015-12-11 16:20:40,704 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CC ......
2015-12-11 16:20:40,706 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:40,735 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CC
Issues: None
2015-12-11 16:20:40,735 export.safeExport INFO     Questionnaire CC updated - 17 new entries received.
2015-12-11 16:20:40,736 export.safeWrite INFO     Writing new entries from CC to active_data/CC_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:40,753 export.safeWrite INFO     Questionnaire CC update finished - 17 new entries recoded successfully.
2015-12-11 16:20:40,754 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/BBSIQ ......
2015-12-11 16:20:40,756 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:40,797 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/BBSIQ
Issues: None
2015-12-11 16:20:40,800 export.safeExport INFO     Questionnaire BBSIQ updated - 25 new entries received.
2015-12-11 16:20:40,801 export.safeWrite INFO     Writing new entries from BBSIQ to active_data/BBSIQ_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:40,936 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:40,939 export.safeWrite INFO     Questionnaire BBSIQ update finished - 25 new entries recoded successfully.
2015-12-11 16:20:40,939 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_DS ......
2015-12-11 16:20:40,940 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:40,987 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_DS
Issues: None
2015-12-11 16:20:40,988 export.safeExport INFO     Questionnaire DASS21_DS updated - 25 new entries received.
2015-12-11 16:20:40,988 export.safeWrite INFO     Writing new entries from DASS21_DS to active_data/DASS21_DS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:41,032 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,032 export.safeWrite INFO     Questionnaire DASS21_DS update finished - 25 new entries recoded successfully.
2015-12-11 16:20:41,033 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/QOL ......
2015-12-11 16:20:41,034 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,088 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/QOL
Issues: None
2015-12-11 16:20:41,093 export.safeExport INFO     Questionnaire QOL updated - 28 new entries received.
2015-12-11 16:20:41,093 export.safeWrite INFO     Writing new entries from QOL to active_data/QOL_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:41,175 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,178 export.safeWrite INFO     Questionnaire QOL update finished - 28 new entries recoded successfully.
2015-12-11 16:20:41,178 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/OA ......
2015-12-11 16:20:41,180 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,348 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/OA
Issues: None
2015-12-11 16:20:41,349 export.safeExport INFO     Questionnaire OA updated - 49 new entries received.
2015-12-11 16:20:41,349 export.safeWrite INFO     Writing new entries from OA to active_data/OA_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:41,418 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,419 export.safeWrite INFO     Questionnaire OA update finished - 49 new entries recoded successfully.
2015-12-11 16:20:41,419 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/RR ......
2015-12-11 16:20:41,421 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,451 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/RR
Issues: None
2015-12-11 16:20:41,453 export.safeExport INFO     Questionnaire RR updated - 25 new entries received.
2015-12-11 16:20:41,453 export.safeWrite INFO     Writing new entries from RR to active_data/RR_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:41,553 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,555 export.safeWrite INFO     Questionnaire RR update finished - 25 new entries recoded successfully.
2015-12-11 16:20:41,556 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImpactAnxiousImagery ......
2015-12-11 16:20:41,557 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,598 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImpactAnxiousImagery
Issues: None
2015-12-11 16:20:41,599 export.safeExport INFO     Questionnaire ImpactAnxiousImagery updated - 36 new entries received.
2015-12-11 16:20:41,599 export.safeWrite INFO     Writing new entries from ImpactAnxiousImagery to active_data/ImpactAnxiousImagery_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:41,633 export.safeWrite INFO     Questionnaire ImpactAnxiousImagery update finished - 36 new entries recoded successfully.
2015-12-11 16:20:41,634 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/SUDS ......
2015-12-11 16:20:41,635 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,666 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/SUDS
Issues: None
2015-12-11 16:20:41,666 export.safeExport INFO     Questionnaire SUDS updated - 43 new entries received.
2015-12-11 16:20:41,667 export.safeWrite INFO     Writing new entries from SUDS to active_data/SUDS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:41,692 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,693 export.safeWrite INFO     Questionnaire SUDS update finished - 43 new entries recoded successfully.
2015-12-11 16:20:41,693 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/PilotUserExperience ......
2015-12-11 16:20:41,696 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,731 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/PilotUserExperience
Issues: None
2015-12-11 16:20:41,731 export.safeExport INFO     No new entries found in PilotUserExperience
2015-12-11 16:20:41,731 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReRu ......
2015-12-11 16:20:41,733 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,762 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReRu
Issues: None
2015-12-11 16:20:41,762 export.safeExport INFO     No new entries found in ReRu
2015-12-11 16:20:41,763 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AnxietyTriggers ......
2015-12-11 16:20:41,764 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,800 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AnxietyTriggers
Issues: None
2015-12-11 16:20:41,801 export.safeExport INFO     Questionnaire AnxietyTriggers updated - 21 new entries received.
2015-12-11 16:20:41,801 export.safeWrite INFO     Writing new entries from AnxietyTriggers to active_data/AnxietyTriggers_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:41,839 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,840 export.safeWrite INFO     Questionnaire AnxietyTriggers update finished - 21 new entries recoded successfully.
2015-12-11 16:20:41,841 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD ......
2015-12-11 16:20:41,842 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,876 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD
Issues: None
2015-12-11 16:20:41,878 export.safeExport INFO     Questionnaire DD updated - 21 new entries received.
2015-12-11 16:20:41,878 export.safeWrite INFO     Writing new entries from DD to active_data/DD_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:41,938 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,941 export.safeWrite INFO     Questionnaire DD update finished - 21 new entries recoded successfully.
2015-12-11 16:20:41,941 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/FollowUp_ChangeInTreatment ......
2015-12-11 16:20:41,943 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:41,975 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/FollowUp_ChangeInTreatment
Issues: None
2015-12-11 16:20:41,976 export.safeExport INFO     No new entries found in FollowUp_ChangeInTreatment
2015-12-11 16:20:41,976 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Credibility ......
2015-12-11 16:20:41,977 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,018 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Credibility
Issues: None
2015-12-11 16:20:42,019 export.safeExport INFO     Questionnaire Credibility updated - 21 new entries received.
2015-12-11 16:20:42,020 export.safeWrite INFO     Writing new entries from Credibility to active_data/Credibility_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:42,051 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:42,052 export.safeWrite INFO     Questionnaire Credibility update finished - 21 new entries recoded successfully.
2015-12-11 16:20:42,053 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MentalHealthHxTx ......
2015-12-11 16:20:42,054 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,178 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MentalHealthHxTx
Issues: None
2015-12-11 16:20:42,180 export.safeExport INFO     Questionnaire MentalHealthHxTx updated - 24 new entries received.
2015-12-11 16:20:42,181 export.safeWrite INFO     Writing new entries from MentalHealthHxTx to active_data/MentalHealthHxTx_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:42,327 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:42,328 export.safeWrite INFO     Questionnaire MentalHealthHxTx update finished - 24 new entries recoded successfully.
2015-12-11 16:20:42,329 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImageryPrime ......
2015-12-11 16:20:42,330 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,364 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImageryPrime
Issues: None
2015-12-11 16:20:42,365 export.safeExport INFO     Questionnaire ImageryPrime updated - 36 new entries received.
2015-12-11 16:20:42,365 export.safeWrite INFO     Writing new entries from ImageryPrime to active_data/ImageryPrime_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:42,414 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:42,415 export.safeWrite INFO     Questionnaire ImageryPrime update finished - 36 new entries recoded successfully.
2015-12-11 16:20:42,416 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReasonsForEnding ......
2015-12-11 16:20:42,418 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,465 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReasonsForEnding
Issues: None
2015-12-11 16:20:42,466 export.safeExport INFO     Questionnaire ReasonsForEnding updated - 3 new entries received.
2015-12-11 16:20:42,467 export.safeWrite INFO     Writing new entries from ReasonsForEnding to active_data/ReasonsForEnding_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:42,483 export.safeWrite INFO     Questionnaire ReasonsForEnding update finished - 3 new entries recoded successfully.
2015-12-11 16:20:42,484 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxietyPost ......
2015-12-11 16:20:42,485 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,519 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxietyPost
Issues: None
2015-12-11 16:20:42,520 export.safeExport INFO     No new entries found in StateAnxietyPost
2015-12-11 16:20:42,520 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Demographic ......
2015-12-11 16:20:42,524 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,559 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Demographic
Issues: None
2015-12-11 16:20:42,560 export.safeExport INFO     Questionnaire Demographic updated - 21 new entries received.
2015-12-11 16:20:42,560 export.safeWrite INFO     Writing new entries from Demographic to active_data/Demographic_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:42,600 export.safeWrite INFO     Questionnaire Demographic update finished - 21 new entries recoded successfully.
2015-12-11 16:20:42,600 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CIHS ......
2015-12-11 16:20:42,602 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,631 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CIHS
Issues: None
2015-12-11 16:20:42,632 export.safeExport INFO     Questionnaire CIHS updated - 2 new entries received.
2015-12-11 16:20:42,632 export.safeWrite INFO     Writing new entries from CIHS to active_data/CIHS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:42,634 export.safeWrite INFO     Questionnaire CIHS update finished - 2 new entries recoded successfully.
2015-12-11 16:20:42,634 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_AS ......
2015-12-11 16:20:42,636 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,755 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_AS
Issues: None
2015-12-11 16:20:42,756 export.safeExport INFO     Questionnaire DASS21_AS updated - 21 new entries received.
2015-12-11 16:20:42,756 export.safeWrite INFO     Writing new entries from DASS21_AS to active_data/DASS21_AS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:42,790 export.safeWrite INFO     Questionnaire DASS21_AS update finished - 21 new entries recoded successfully.
2015-12-11 16:20:42,791 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD_FU ......
2015-12-11 16:20:42,792 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:20:42,822 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD_FU
Issues: None
2015-12-11 16:20:42,823 export.safeExport INFO     Questionnaire DD_FU updated - 5 new entries received.
2015-12-11 16:20:42,823 export.safeWrite INFO     Writing new entries from DD_FU to active_data/DD_FU_Dec_11_2015.csv: writing in progress......
2015-12-11 16:20:42,831 export.safeWrite INFO     Questionnaire DD_FU update finished - 5 new entries recoded successfully.
2015-12-11 16:20:42,832 export.safeExport INFO     Database update finished: 19 questionnaires' data updated.
2015-12-11 16:22:43,826 export          INFO     Hi PACT Lab, this is faithful android Martin from Laura's server. Everything is alright here, and seems to be
     a good time for a hunt. I am going out for a regular check and will come back soon. Don't miss me PACT Lab, it wouldn't
     take too long.
2015-12-11 16:22:43,827 export          INFO      (Martin is out for hunting data......) 
2015-12-11 16:22:43,827 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export ......
2015-12-11 16:22:43,837 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:43,904 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export
Issues: None
2015-12-11 16:22:43,904 export          INFO     Alright I am back! Pretty fruitful. Seem like it is going to be comfortable for a little while. Alright,
     I am heading to the server for a little rest, will talk to you guys in PACT Lab in a little while. -- Martin
2015-12-11 16:22:43,905 export.safeExport INFO     Database update in progress......
2015-12-11 16:22:43,905 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxiety ......
2015-12-11 16:22:43,906 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,094 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxiety
Issues: None
2015-12-11 16:22:44,095 export.safeExport INFO     No new entries found in StateAnxiety
2015-12-11 16:22:44,095 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AUDIT ......
2015-12-11 16:22:44,096 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,136 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AUDIT
Issues: None
2015-12-11 16:22:44,136 export.safeExport INFO     No new entries found in AUDIT
2015-12-11 16:22:44,136 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MultiUserExperience ......
2015-12-11 16:22:44,138 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,163 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MultiUserExperience
Issues: None
2015-12-11 16:22:44,163 export.safeExport INFO     Questionnaire MultiUserExperience updated - 2 new entries received.
2015-12-11 16:22:44,163 export.safeWrite INFO     Writing new entries from MultiUserExperience to active_data/MultiUserExperience_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:44,180 export.safeWrite INFO     Questionnaire MultiUserExperience update finished - 2 new entries recoded successfully.
2015-12-11 16:22:44,183 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Vivid ......
2015-12-11 16:22:44,188 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,234 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Vivid
Issues: None
2015-12-11 16:22:44,234 export.safeExport INFO     No new entries found in Vivid
2015-12-11 16:22:44,234 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CC ......
2015-12-11 16:22:44,235 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,282 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CC
Issues: None
2015-12-11 16:22:44,282 export.safeExport INFO     Questionnaire CC updated - 17 new entries received.
2015-12-11 16:22:44,282 export.safeWrite INFO     Writing new entries from CC to active_data/CC_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:44,300 export.safeWrite INFO     Questionnaire CC update finished - 17 new entries recoded successfully.
2015-12-11 16:22:44,301 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/BBSIQ ......
2015-12-11 16:22:44,302 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,330 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/BBSIQ
Issues: None
2015-12-11 16:22:44,332 export.safeExport INFO     Questionnaire BBSIQ updated - 25 new entries received.
2015-12-11 16:22:44,332 export.safeWrite INFO     Writing new entries from BBSIQ to active_data/BBSIQ_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:44,486 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:44,493 export.safeWrite INFO     Questionnaire BBSIQ update finished - 25 new entries recoded successfully.
2015-12-11 16:22:44,493 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_DS ......
2015-12-11 16:22:44,494 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,527 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_DS
Issues: None
2015-12-11 16:22:44,528 export.safeExport INFO     Questionnaire DASS21_DS updated - 25 new entries received.
2015-12-11 16:22:44,528 export.safeWrite INFO     Writing new entries from DASS21_DS to active_data/DASS21_DS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:44,574 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:44,575 export.safeWrite INFO     Questionnaire DASS21_DS update finished - 25 new entries recoded successfully.
2015-12-11 16:22:44,576 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/QOL ......
2015-12-11 16:22:44,577 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,614 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/QOL
Issues: None
2015-12-11 16:22:44,617 export.safeExport INFO     Questionnaire QOL updated - 28 new entries received.
2015-12-11 16:22:44,617 export.safeWrite INFO     Writing new entries from QOL to active_data/QOL_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:44,693 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:44,695 export.safeWrite INFO     Questionnaire QOL update finished - 28 new entries recoded successfully.
2015-12-11 16:22:44,698 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/OA ......
2015-12-11 16:22:44,700 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,849 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/OA
Issues: None
2015-12-11 16:22:44,850 export.safeExport INFO     Questionnaire OA updated - 49 new entries received.
2015-12-11 16:22:44,850 export.safeWrite INFO     Writing new entries from OA to active_data/OA_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:44,923 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:44,923 export.safeWrite INFO     Questionnaire OA update finished - 49 new entries recoded successfully.
2015-12-11 16:22:44,924 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/RR ......
2015-12-11 16:22:44,925 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:44,959 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/RR
Issues: None
2015-12-11 16:22:44,960 export.safeExport INFO     Questionnaire RR updated - 25 new entries received.
2015-12-11 16:22:44,961 export.safeWrite INFO     Writing new entries from RR to active_data/RR_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,077 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,079 export.safeWrite INFO     Questionnaire RR update finished - 25 new entries recoded successfully.
2015-12-11 16:22:45,079 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImpactAnxiousImagery ......
2015-12-11 16:22:45,081 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,111 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImpactAnxiousImagery
Issues: None
2015-12-11 16:22:45,112 export.safeExport INFO     Questionnaire ImpactAnxiousImagery updated - 36 new entries received.
2015-12-11 16:22:45,112 export.safeWrite INFO     Writing new entries from ImpactAnxiousImagery to active_data/ImpactAnxiousImagery_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,153 export.safeWrite INFO     Questionnaire ImpactAnxiousImagery update finished - 36 new entries recoded successfully.
2015-12-11 16:22:45,154 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/SUDS ......
2015-12-11 16:22:45,155 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,185 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/SUDS
Issues: None
2015-12-11 16:22:45,185 export.safeExport INFO     Questionnaire SUDS updated - 43 new entries received.
2015-12-11 16:22:45,186 export.safeWrite INFO     Writing new entries from SUDS to active_data/SUDS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,221 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,222 export.safeWrite INFO     Questionnaire SUDS update finished - 43 new entries recoded successfully.
2015-12-11 16:22:45,222 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/PilotUserExperience ......
2015-12-11 16:22:45,223 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,251 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/PilotUserExperience
Issues: None
2015-12-11 16:22:45,251 export.safeExport INFO     No new entries found in PilotUserExperience
2015-12-11 16:22:45,252 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReRu ......
2015-12-11 16:22:45,253 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,281 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReRu
Issues: None
2015-12-11 16:22:45,282 export.safeExport INFO     No new entries found in ReRu
2015-12-11 16:22:45,282 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AnxietyTriggers ......
2015-12-11 16:22:45,283 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,315 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AnxietyTriggers
Issues: None
2015-12-11 16:22:45,316 export.safeExport INFO     Questionnaire AnxietyTriggers updated - 21 new entries received.
2015-12-11 16:22:45,316 export.safeWrite INFO     Writing new entries from AnxietyTriggers to active_data/AnxietyTriggers_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,355 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,356 export.safeWrite INFO     Questionnaire AnxietyTriggers update finished - 21 new entries recoded successfully.
2015-12-11 16:22:45,357 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD ......
2015-12-11 16:22:45,358 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,391 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD
Issues: None
2015-12-11 16:22:45,392 export.safeExport INFO     Questionnaire DD updated - 21 new entries received.
2015-12-11 16:22:45,392 export.safeWrite INFO     Writing new entries from DD to active_data/DD_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,445 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,447 export.safeWrite INFO     Questionnaire DD update finished - 21 new entries recoded successfully.
2015-12-11 16:22:45,448 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/FollowUp_ChangeInTreatment ......
2015-12-11 16:22:45,449 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,482 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/FollowUp_ChangeInTreatment
Issues: None
2015-12-11 16:22:45,482 export.safeExport INFO     No new entries found in FollowUp_ChangeInTreatment
2015-12-11 16:22:45,482 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Credibility ......
2015-12-11 16:22:45,484 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,510 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Credibility
Issues: None
2015-12-11 16:22:45,510 export.safeExport INFO     Questionnaire Credibility updated - 21 new entries received.
2015-12-11 16:22:45,510 export.safeWrite INFO     Writing new entries from Credibility to active_data/Credibility_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,526 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,526 export.safeWrite INFO     Questionnaire Credibility update finished - 21 new entries recoded successfully.
2015-12-11 16:22:45,527 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MentalHealthHxTx ......
2015-12-11 16:22:45,528 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,613 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MentalHealthHxTx
Issues: None
2015-12-11 16:22:45,616 export.safeExport INFO     Questionnaire MentalHealthHxTx updated - 24 new entries received.
2015-12-11 16:22:45,616 export.safeWrite INFO     Writing new entries from MentalHealthHxTx to active_data/MentalHealthHxTx_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,734 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,736 export.safeWrite INFO     Questionnaire MentalHealthHxTx update finished - 24 new entries recoded successfully.
2015-12-11 16:22:45,736 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImageryPrime ......
2015-12-11 16:22:45,738 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,775 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImageryPrime
Issues: None
2015-12-11 16:22:45,776 export.safeExport INFO     Questionnaire ImageryPrime updated - 36 new entries received.
2015-12-11 16:22:45,777 export.safeWrite INFO     Writing new entries from ImageryPrime to active_data/ImageryPrime_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,817 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,818 export.safeWrite INFO     Questionnaire ImageryPrime update finished - 36 new entries recoded successfully.
2015-12-11 16:22:45,819 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReasonsForEnding ......
2015-12-11 16:22:45,820 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,868 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReasonsForEnding
Issues: None
2015-12-11 16:22:45,869 export.safeExport INFO     Questionnaire ReasonsForEnding updated - 3 new entries received.
2015-12-11 16:22:45,869 export.safeWrite INFO     Writing new entries from ReasonsForEnding to active_data/ReasonsForEnding_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:45,880 export.safeWrite INFO     Questionnaire ReasonsForEnding update finished - 3 new entries recoded successfully.
2015-12-11 16:22:45,880 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxietyPost ......
2015-12-11 16:22:45,882 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,912 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxietyPost
Issues: None
2015-12-11 16:22:45,912 export.safeExport INFO     No new entries found in StateAnxietyPost
2015-12-11 16:22:45,912 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Demographic ......
2015-12-11 16:22:45,914 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:45,962 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Demographic
Issues: None
2015-12-11 16:22:45,962 export.safeExport INFO     Questionnaire Demographic updated - 21 new entries received.
2015-12-11 16:22:45,962 export.safeWrite INFO     Writing new entries from Demographic to active_data/Demographic_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:46,005 export.safeWrite INFO     Questionnaire Demographic update finished - 21 new entries recoded successfully.
2015-12-11 16:22:46,005 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CIHS ......
2015-12-11 16:22:46,007 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:46,041 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CIHS
Issues: None
2015-12-11 16:22:46,041 export.safeExport INFO     Questionnaire CIHS updated - 2 new entries received.
2015-12-11 16:22:46,042 export.safeWrite INFO     Writing new entries from CIHS to active_data/CIHS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:46,045 export.safeWrite INFO     Questionnaire CIHS update finished - 2 new entries recoded successfully.
2015-12-11 16:22:46,048 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_AS ......
2015-12-11 16:22:46,052 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:46,164 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_AS
Issues: None
2015-12-11 16:22:46,165 export.safeExport INFO     Questionnaire DASS21_AS updated - 21 new entries received.
2015-12-11 16:22:46,165 export.safeWrite INFO     Writing new entries from DASS21_AS to active_data/DASS21_AS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:46,202 export.safeWrite INFO     Questionnaire DASS21_AS update finished - 21 new entries recoded successfully.
2015-12-11 16:22:46,203 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD_FU ......
2015-12-11 16:22:46,204 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:22:46,233 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD_FU
Issues: None
2015-12-11 16:22:46,233 export.safeExport INFO     Questionnaire DD_FU updated - 5 new entries received.
2015-12-11 16:22:46,234 export.safeWrite INFO     Writing new entries from DD_FU to active_data/DD_FU_Dec_11_2015.csv: writing in progress......
2015-12-11 16:22:46,246 export.safeWrite INFO     Questionnaire DD_FU update finished - 5 new entries recoded successfully.
2015-12-11 16:22:46,247 export.safeExport INFO     Database update finished: 19 questionnaires' data updated.
2015-12-11 16:23:03,046 export          INFO     Hi PACT Lab, this is faithful android Martin from Laura's server. Everything is alright here, and seems to be
     a good time for a hunt. I am going out for a regular check and will come back soon. Don't miss me PACT Lab, it wouldn't
     take too long.
2015-12-11 16:23:03,046 export          INFO      (Martin is out for hunting data......) 
2015-12-11 16:23:03,046 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export ......
2015-12-11 16:23:03,054 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,119 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export
Issues: None
2015-12-11 16:23:03,120 export          INFO     Alright I am back! Pretty fruitful. Seem like it is going to be comfortable for a little while. Alright,
     I am heading to the server for a little rest, will talk to you guys in PACT Lab in a little while. -- Martin
2015-12-11 16:23:03,120 export.safeExport INFO     Database update in progress......
2015-12-11 16:23:03,120 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxiety ......
2015-12-11 16:23:03,122 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,140 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxiety
Issues: None
2015-12-11 16:23:03,140 export.safeExport INFO     No new entries found in StateAnxiety
2015-12-11 16:23:03,140 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AUDIT ......
2015-12-11 16:23:03,141 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,172 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AUDIT
Issues: None
2015-12-11 16:23:03,172 export.safeExport INFO     No new entries found in AUDIT
2015-12-11 16:23:03,173 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MultiUserExperience ......
2015-12-11 16:23:03,175 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,209 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MultiUserExperience
Issues: None
2015-12-11 16:23:03,210 export.safeExport INFO     Questionnaire MultiUserExperience updated - 2 new entries received.
2015-12-11 16:23:03,210 export.safeWrite INFO     Writing new entries from MultiUserExperience to active_data/MultiUserExperience_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:03,220 export.safeWrite INFO     Questionnaire MultiUserExperience update finished - 2 new entries recoded successfully.
2015-12-11 16:23:03,221 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Vivid ......
2015-12-11 16:23:03,223 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,270 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Vivid
Issues: None
2015-12-11 16:23:03,271 export.safeExport INFO     No new entries found in Vivid
2015-12-11 16:23:03,271 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CC ......
2015-12-11 16:23:03,277 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,339 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CC
Issues: None
2015-12-11 16:23:03,340 export.safeExport INFO     Questionnaire CC updated - 17 new entries received.
2015-12-11 16:23:03,340 export.safeWrite INFO     Writing new entries from CC to active_data/CC_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:03,356 export.safeWrite INFO     Questionnaire CC update finished - 17 new entries recoded successfully.
2015-12-11 16:23:03,356 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/BBSIQ ......
2015-12-11 16:23:03,357 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,482 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/BBSIQ
Issues: None
2015-12-11 16:23:03,484 export.safeExport INFO     Questionnaire BBSIQ updated - 25 new entries received.
2015-12-11 16:23:03,484 export.safeWrite INFO     Writing new entries from BBSIQ to active_data/BBSIQ_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:03,636 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:03,640 export.safeWrite INFO     Questionnaire BBSIQ update finished - 25 new entries recoded successfully.
2015-12-11 16:23:03,641 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_DS ......
2015-12-11 16:23:03,642 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,673 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_DS
Issues: None
2015-12-11 16:23:03,674 export.safeExport INFO     Questionnaire DASS21_DS updated - 25 new entries received.
2015-12-11 16:23:03,674 export.safeWrite INFO     Writing new entries from DASS21_DS to active_data/DASS21_DS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:03,712 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:03,713 export.safeWrite INFO     Questionnaire DASS21_DS update finished - 25 new entries recoded successfully.
2015-12-11 16:23:03,714 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/QOL ......
2015-12-11 16:23:03,716 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,745 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/QOL
Issues: None
2015-12-11 16:23:03,746 export.safeExport INFO     Questionnaire QOL updated - 28 new entries received.
2015-12-11 16:23:03,747 export.safeWrite INFO     Writing new entries from QOL to active_data/QOL_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:03,816 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:03,818 export.safeWrite INFO     Questionnaire QOL update finished - 28 new entries recoded successfully.
2015-12-11 16:23:03,818 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/OA ......
2015-12-11 16:23:03,820 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:03,959 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/OA
Issues: None
2015-12-11 16:23:03,960 export.safeExport INFO     Questionnaire OA updated - 49 new entries received.
2015-12-11 16:23:03,960 export.safeWrite INFO     Writing new entries from OA to active_data/OA_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,025 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,026 export.safeWrite INFO     Questionnaire OA update finished - 49 new entries recoded successfully.
2015-12-11 16:23:04,032 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/RR ......
2015-12-11 16:23:04,033 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,077 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/RR
Issues: None
2015-12-11 16:23:04,079 export.safeExport INFO     Questionnaire RR updated - 25 new entries received.
2015-12-11 16:23:04,080 export.safeWrite INFO     Writing new entries from RR to active_data/RR_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,173 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,176 export.safeWrite INFO     Questionnaire RR update finished - 25 new entries recoded successfully.
2015-12-11 16:23:04,176 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImpactAnxiousImagery ......
2015-12-11 16:23:04,177 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,280 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImpactAnxiousImagery
Issues: None
2015-12-11 16:23:04,281 export.safeExport INFO     Questionnaire ImpactAnxiousImagery updated - 36 new entries received.
2015-12-11 16:23:04,281 export.safeWrite INFO     Writing new entries from ImpactAnxiousImagery to active_data/ImpactAnxiousImagery_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,323 export.safeWrite INFO     Questionnaire ImpactAnxiousImagery update finished - 36 new entries recoded successfully.
2015-12-11 16:23:04,324 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/SUDS ......
2015-12-11 16:23:04,325 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,366 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/SUDS
Issues: None
2015-12-11 16:23:04,367 export.safeExport INFO     Questionnaire SUDS updated - 43 new entries received.
2015-12-11 16:23:04,367 export.safeWrite INFO     Writing new entries from SUDS to active_data/SUDS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,405 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,406 export.safeWrite INFO     Questionnaire SUDS update finished - 43 new entries recoded successfully.
2015-12-11 16:23:04,407 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/PilotUserExperience ......
2015-12-11 16:23:04,409 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,441 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/PilotUserExperience
Issues: None
2015-12-11 16:23:04,441 export.safeExport INFO     No new entries found in PilotUserExperience
2015-12-11 16:23:04,441 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReRu ......
2015-12-11 16:23:04,443 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,476 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReRu
Issues: None
2015-12-11 16:23:04,476 export.safeExport INFO     No new entries found in ReRu
2015-12-11 16:23:04,477 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AnxietyTriggers ......
2015-12-11 16:23:04,478 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,509 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AnxietyTriggers
Issues: None
2015-12-11 16:23:04,511 export.safeExport INFO     Questionnaire AnxietyTriggers updated - 21 new entries received.
2015-12-11 16:23:04,511 export.safeWrite INFO     Writing new entries from AnxietyTriggers to active_data/AnxietyTriggers_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,551 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,552 export.safeWrite INFO     Questionnaire AnxietyTriggers update finished - 21 new entries recoded successfully.
2015-12-11 16:23:04,553 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD ......
2015-12-11 16:23:04,555 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,588 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD
Issues: None
2015-12-11 16:23:04,589 export.safeExport INFO     Questionnaire DD updated - 21 new entries received.
2015-12-11 16:23:04,590 export.safeWrite INFO     Writing new entries from DD to active_data/DD_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,644 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,646 export.safeWrite INFO     Questionnaire DD update finished - 21 new entries recoded successfully.
2015-12-11 16:23:04,646 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/FollowUp_ChangeInTreatment ......
2015-12-11 16:23:04,648 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,678 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/FollowUp_ChangeInTreatment
Issues: None
2015-12-11 16:23:04,678 export.safeExport INFO     No new entries found in FollowUp_ChangeInTreatment
2015-12-11 16:23:04,678 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Credibility ......
2015-12-11 16:23:04,679 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,708 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Credibility
Issues: None
2015-12-11 16:23:04,709 export.safeExport INFO     Questionnaire Credibility updated - 21 new entries received.
2015-12-11 16:23:04,709 export.safeWrite INFO     Writing new entries from Credibility to active_data/Credibility_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,729 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,730 export.safeWrite INFO     Questionnaire Credibility update finished - 21 new entries recoded successfully.
2015-12-11 16:23:04,730 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MentalHealthHxTx ......
2015-12-11 16:23:04,732 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,805 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MentalHealthHxTx
Issues: None
2015-12-11 16:23:04,806 export.safeExport INFO     Questionnaire MentalHealthHxTx updated - 24 new entries received.
2015-12-11 16:23:04,806 export.safeWrite INFO     Writing new entries from MentalHealthHxTx to active_data/MentalHealthHxTx_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,905 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,907 export.safeWrite INFO     Questionnaire MentalHealthHxTx update finished - 24 new entries recoded successfully.
2015-12-11 16:23:04,907 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImageryPrime ......
2015-12-11 16:23:04,908 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:04,938 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImageryPrime
Issues: None
2015-12-11 16:23:04,939 export.safeExport INFO     Questionnaire ImageryPrime updated - 36 new entries received.
2015-12-11 16:23:04,940 export.safeWrite INFO     Writing new entries from ImageryPrime to active_data/ImageryPrime_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:04,973 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,974 export.safeWrite INFO     Questionnaire ImageryPrime update finished - 36 new entries recoded successfully.
2015-12-11 16:23:04,975 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReasonsForEnding ......
2015-12-11 16:23:04,976 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:05,011 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReasonsForEnding
Issues: None
2015-12-11 16:23:05,011 export.safeExport INFO     Questionnaire ReasonsForEnding updated - 3 new entries received.
2015-12-11 16:23:05,011 export.safeWrite INFO     Writing new entries from ReasonsForEnding to active_data/ReasonsForEnding_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:05,021 export.safeWrite INFO     Questionnaire ReasonsForEnding update finished - 3 new entries recoded successfully.
2015-12-11 16:23:05,022 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxietyPost ......
2015-12-11 16:23:05,023 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:05,057 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxietyPost
Issues: None
2015-12-11 16:23:05,057 export.safeExport INFO     No new entries found in StateAnxietyPost
2015-12-11 16:23:05,058 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Demographic ......
2015-12-11 16:23:05,059 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:05,107 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Demographic
Issues: None
2015-12-11 16:23:05,108 export.safeExport INFO     Questionnaire Demographic updated - 21 new entries received.
2015-12-11 16:23:05,108 export.safeWrite INFO     Writing new entries from Demographic to active_data/Demographic_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:05,152 export.safeWrite INFO     Questionnaire Demographic update finished - 21 new entries recoded successfully.
2015-12-11 16:23:05,153 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CIHS ......
2015-12-11 16:23:05,162 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:05,191 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CIHS
Issues: None
2015-12-11 16:23:05,192 export.safeExport INFO     Questionnaire CIHS updated - 2 new entries received.
2015-12-11 16:23:05,192 export.safeWrite INFO     Writing new entries from CIHS to active_data/CIHS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:05,197 export.safeWrite INFO     Questionnaire CIHS update finished - 2 new entries recoded successfully.
2015-12-11 16:23:05,198 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_AS ......
2015-12-11 16:23:05,199 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:05,328 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_AS
Issues: None
2015-12-11 16:23:05,328 export.safeExport INFO     Questionnaire DASS21_AS updated - 21 new entries received.
2015-12-11 16:23:05,329 export.safeWrite INFO     Writing new entries from DASS21_AS to active_data/DASS21_AS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:05,373 export.safeWrite INFO     Questionnaire DASS21_AS update finished - 21 new entries recoded successfully.
2015-12-11 16:23:05,373 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD_FU ......
2015-12-11 16:23:05,375 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:23:05,410 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD_FU
Issues: None
2015-12-11 16:23:05,410 export.safeExport INFO     Questionnaire DD_FU updated - 5 new entries received.
2015-12-11 16:23:05,411 export.safeWrite INFO     Writing new entries from DD_FU to active_data/DD_FU_Dec_11_2015.csv: writing in progress......
2015-12-11 16:23:05,436 export.safeWrite INFO     Questionnaire DD_FU update finished - 5 new entries recoded successfully.
2015-12-11 16:23:05,437 export.safeExport INFO     Database update finished: 19 questionnaires' data updated.
2015-12-11 16:31:59,352 export          INFO     Hi PACT Lab, this is faithful android Martin from Laura's server. Everything is alright here, and seems to be
     a good time for a hunt. I am going out for a regular check and will come back soon. Don't miss me PACT Lab, it wouldn't
     take too long.
2015-12-11 16:31:59,353 export          INFO      (Martin is out for hunting data......) 
2015-12-11 16:31:59,353 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export ......
2015-12-11 16:31:59,368 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:31:59,448 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export
Issues: None
2015-12-11 16:31:59,449 export          INFO     Alright I am back! Pretty fruitful. Seem like it is going to be comfortable for a little while. Alright,
     I am heading to the server for a little rest, will talk to you guys in PACT Lab in a little while. -- Martin
2015-12-11 16:31:59,449 export.safeExport INFO     Database update in progress......
2015-12-11 16:31:59,449 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxiety ......
2015-12-11 16:31:59,451 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:31:59,528 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxiety
Issues: None
2015-12-11 16:31:59,529 export.safeExport INFO     No new entries found in StateAnxiety
2015-12-11 16:31:59,529 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AUDIT ......
2015-12-11 16:31:59,530 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:31:59,598 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AUDIT
Issues: None
2015-12-11 16:31:59,599 export.safeExport INFO     No new entries found in AUDIT
2015-12-11 16:31:59,599 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MultiUserExperience ......
2015-12-11 16:31:59,601 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:31:59,671 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MultiUserExperience
Issues: None
2015-12-11 16:31:59,672 export.safeExport INFO     Questionnaire MultiUserExperience updated - 2 new entries received.
2015-12-11 16:31:59,672 export.safeWrite INFO     Writing new entries from MultiUserExperience to active_data/MultiUserExperience_Dec_11_2015.csv: writing in progress......
2015-12-11 16:31:59,691 export.safeKeep INFO     MultiUserExperience data successfully backup as raw data.
2015-12-11 16:31:59,702 export.safeWrite INFO     Questionnaire MultiUserExperience update finished - 2 new entries recoded successfully.
2015-12-11 16:31:59,703 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Vivid ......
2015-12-11 16:31:59,705 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:31:59,750 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Vivid
Issues: None
2015-12-11 16:31:59,751 export.safeExport INFO     No new entries found in Vivid
2015-12-11 16:31:59,752 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CC ......
2015-12-11 16:31:59,754 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:31:59,791 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CC
Issues: None
2015-12-11 16:31:59,791 export.safeExport INFO     Questionnaire CC updated - 17 new entries received.
2015-12-11 16:31:59,792 export.safeWrite INFO     Writing new entries from CC to active_data/CC_Dec_11_2015.csv: writing in progress......
2015-12-11 16:31:59,795 export.safeKeep INFO     CC data successfully backup as raw data.
2015-12-11 16:31:59,819 export.safeWrite INFO     Questionnaire CC update finished - 17 new entries recoded successfully.
2015-12-11 16:31:59,820 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/BBSIQ ......
2015-12-11 16:31:59,822 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:31:59,860 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/BBSIQ
Issues: None
2015-12-11 16:31:59,864 export.safeExport INFO     Questionnaire BBSIQ updated - 25 new entries received.
2015-12-11 16:31:59,865 export.safeWrite INFO     Writing new entries from BBSIQ to active_data/BBSIQ_Dec_11_2015.csv: writing in progress......
2015-12-11 16:31:59,876 export.safeKeep INFO     BBSIQ data successfully backup as raw data.
2015-12-11 16:32:00,020 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,024 export.safeWrite INFO     Questionnaire BBSIQ update finished - 25 new entries recoded successfully.
2015-12-11 16:32:00,024 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_DS ......
2015-12-11 16:32:00,026 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,059 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_DS
Issues: None
2015-12-11 16:32:00,060 export.safeExport INFO     Questionnaire DASS21_DS updated - 25 new entries received.
2015-12-11 16:32:00,060 export.safeWrite INFO     Writing new entries from DASS21_DS to active_data/DASS21_DS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:00,062 export.safeKeep INFO     DASS21_DS data successfully backup as raw data.
2015-12-11 16:32:00,101 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,102 export.safeWrite INFO     Questionnaire DASS21_DS update finished - 25 new entries recoded successfully.
2015-12-11 16:32:00,103 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/QOL ......
2015-12-11 16:32:00,104 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,168 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/QOL
Issues: None
2015-12-11 16:32:00,173 export.safeExport INFO     Questionnaire QOL updated - 28 new entries received.
2015-12-11 16:32:00,174 export.safeWrite INFO     Writing new entries from QOL to active_data/QOL_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:00,177 export.safeKeep INFO     QOL data successfully backup as raw data.
2015-12-11 16:32:00,256 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,258 export.safeWrite INFO     Questionnaire QOL update finished - 28 new entries recoded successfully.
2015-12-11 16:32:00,260 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/OA ......
2015-12-11 16:32:00,262 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,413 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/OA
Issues: None
2015-12-11 16:32:00,414 export.safeExport INFO     Questionnaire OA updated - 49 new entries received.
2015-12-11 16:32:00,414 export.safeWrite INFO     Writing new entries from OA to active_data/OA_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:00,417 export.safeKeep INFO     OA data successfully backup as raw data.
2015-12-11 16:32:00,483 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,484 export.safeWrite INFO     Questionnaire OA update finished - 49 new entries recoded successfully.
2015-12-11 16:32:00,485 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/RR ......
2015-12-11 16:32:00,486 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,520 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/RR
Issues: None
2015-12-11 16:32:00,521 export.safeExport INFO     Questionnaire RR updated - 25 new entries received.
2015-12-11 16:32:00,521 export.safeWrite INFO     Writing new entries from RR to active_data/RR_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:00,524 export.safeKeep INFO     RR data successfully backup as raw data.
2015-12-11 16:32:00,626 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,628 export.safeWrite INFO     Questionnaire RR update finished - 25 new entries recoded successfully.
2015-12-11 16:32:00,629 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImpactAnxiousImagery ......
2015-12-11 16:32:00,630 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,663 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImpactAnxiousImagery
Issues: None
2015-12-11 16:32:00,664 export.safeExport INFO     Questionnaire ImpactAnxiousImagery updated - 36 new entries received.
2015-12-11 16:32:00,664 export.safeWrite INFO     Writing new entries from ImpactAnxiousImagery to active_data/ImpactAnxiousImagery_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:00,668 export.safeKeep INFO     ImpactAnxiousImagery data successfully backup as raw data.
2015-12-11 16:32:00,703 export.safeWrite INFO     Questionnaire ImpactAnxiousImagery update finished - 36 new entries recoded successfully.
2015-12-11 16:32:00,703 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/SUDS ......
2015-12-11 16:32:00,705 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,746 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/SUDS
Issues: None
2015-12-11 16:32:00,747 export.safeExport INFO     Questionnaire SUDS updated - 43 new entries received.
2015-12-11 16:32:00,747 export.safeWrite INFO     Writing new entries from SUDS to active_data/SUDS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:00,753 export.safeKeep INFO     SUDS data successfully backup as raw data.
2015-12-11 16:32:00,783 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,784 export.safeWrite INFO     Questionnaire SUDS update finished - 43 new entries recoded successfully.
2015-12-11 16:32:00,784 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/PilotUserExperience ......
2015-12-11 16:32:00,786 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,822 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/PilotUserExperience
Issues: None
2015-12-11 16:32:00,822 export.safeExport INFO     No new entries found in PilotUserExperience
2015-12-11 16:32:00,822 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReRu ......
2015-12-11 16:32:00,823 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,859 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReRu
Issues: None
2015-12-11 16:32:00,859 export.safeExport INFO     No new entries found in ReRu
2015-12-11 16:32:00,859 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/AnxietyTriggers ......
2015-12-11 16:32:00,862 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,895 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/AnxietyTriggers
Issues: None
2015-12-11 16:32:00,895 export.safeExport INFO     Questionnaire AnxietyTriggers updated - 21 new entries received.
2015-12-11 16:32:00,895 export.safeWrite INFO     Writing new entries from AnxietyTriggers to active_data/AnxietyTriggers_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:00,900 export.safeKeep INFO     AnxietyTriggers data successfully backup as raw data.
2015-12-11 16:32:00,926 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,927 export.safeWrite INFO     Questionnaire AnxietyTriggers update finished - 21 new entries recoded successfully.
2015-12-11 16:32:00,928 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD ......
2015-12-11 16:32:00,929 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:00,966 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD
Issues: None
2015-12-11 16:32:00,967 export.safeExport INFO     Questionnaire DD updated - 21 new entries received.
2015-12-11 16:32:00,967 export.safeWrite INFO     Writing new entries from DD to active_data/DD_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:00,970 export.safeKeep INFO     DD data successfully backup as raw data.
2015-12-11 16:32:01,009 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:01,011 export.safeWrite INFO     Questionnaire DD update finished - 21 new entries recoded successfully.
2015-12-11 16:32:01,011 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/FollowUp_ChangeInTreatment ......
2015-12-11 16:32:01,012 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,042 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/FollowUp_ChangeInTreatment
Issues: None
2015-12-11 16:32:01,043 export.safeExport INFO     No new entries found in FollowUp_ChangeInTreatment
2015-12-11 16:32:01,043 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Credibility ......
2015-12-11 16:32:01,044 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,078 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Credibility
Issues: None
2015-12-11 16:32:01,079 export.safeExport INFO     Questionnaire Credibility updated - 21 new entries received.
2015-12-11 16:32:01,079 export.safeWrite INFO     Writing new entries from Credibility to active_data/Credibility_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:01,081 export.safeKeep INFO     Credibility data successfully backup as raw data.
2015-12-11 16:32:01,101 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:01,102 export.safeWrite INFO     Questionnaire Credibility update finished - 21 new entries recoded successfully.
2015-12-11 16:32:01,102 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/MentalHealthHxTx ......
2015-12-11 16:32:01,104 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,186 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/MentalHealthHxTx
Issues: None
2015-12-11 16:32:01,188 export.safeExport INFO     Questionnaire MentalHealthHxTx updated - 24 new entries received.
2015-12-11 16:32:01,188 export.safeWrite INFO     Writing new entries from MentalHealthHxTx to active_data/MentalHealthHxTx_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:01,191 export.safeKeep INFO     MentalHealthHxTx data successfully backup as raw data.
2015-12-11 16:32:01,316 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:01,318 export.safeWrite INFO     Questionnaire MentalHealthHxTx update finished - 24 new entries recoded successfully.
2015-12-11 16:32:01,318 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ImageryPrime ......
2015-12-11 16:32:01,319 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,352 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ImageryPrime
Issues: None
2015-12-11 16:32:01,353 export.safeExport INFO     Questionnaire ImageryPrime updated - 36 new entries received.
2015-12-11 16:32:01,353 export.safeWrite INFO     Writing new entries from ImageryPrime to active_data/ImageryPrime_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:01,355 export.safeKeep INFO     ImageryPrime data successfully backup as raw data.
2015-12-11 16:32:01,393 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:01,393 export.safeWrite INFO     Questionnaire ImageryPrime update finished - 36 new entries recoded successfully.
2015-12-11 16:32:01,394 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/ReasonsForEnding ......
2015-12-11 16:32:01,396 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,432 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/ReasonsForEnding
Issues: None
2015-12-11 16:32:01,432 export.safeExport INFO     Questionnaire ReasonsForEnding updated - 3 new entries received.
2015-12-11 16:32:01,433 export.safeWrite INFO     Writing new entries from ReasonsForEnding to active_data/ReasonsForEnding_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:01,434 export.safeKeep INFO     ReasonsForEnding data successfully backup as raw data.
2015-12-11 16:32:01,447 export.safeWrite INFO     Questionnaire ReasonsForEnding update finished - 3 new entries recoded successfully.
2015-12-11 16:32:01,448 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/StateAnxietyPost ......
2015-12-11 16:32:01,449 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,483 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/StateAnxietyPost
Issues: None
2015-12-11 16:32:01,484 export.safeExport INFO     No new entries found in StateAnxietyPost
2015-12-11 16:32:01,484 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/Demographic ......
2015-12-11 16:32:01,485 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,515 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/Demographic
Issues: None
2015-12-11 16:32:01,515 export.safeExport INFO     Questionnaire Demographic updated - 21 new entries received.
2015-12-11 16:32:01,515 export.safeWrite INFO     Writing new entries from Demographic to active_data/Demographic_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:01,518 export.safeKeep INFO     Demographic data successfully backup as raw data.
2015-12-11 16:32:01,560 export.safeWrite INFO     Questionnaire Demographic update finished - 21 new entries recoded successfully.
2015-12-11 16:32:01,561 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/CIHS ......
2015-12-11 16:32:01,562 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,594 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/CIHS
Issues: None
2015-12-11 16:32:01,595 export.safeExport INFO     Questionnaire CIHS updated - 2 new entries received.
2015-12-11 16:32:01,595 export.safeWrite INFO     Writing new entries from CIHS to active_data/CIHS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:01,596 export.safeKeep INFO     CIHS data successfully backup as raw data.
2015-12-11 16:32:01,598 export.safeWrite INFO     Questionnaire CIHS update finished - 2 new entries recoded successfully.
2015-12-11 16:32:01,599 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DASS21_AS ......
2015-12-11 16:32:01,600 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,703 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DASS21_AS
Issues: None
2015-12-11 16:32:01,704 export.safeExport INFO     Questionnaire DASS21_AS updated - 21 new entries received.
2015-12-11 16:32:01,705 export.safeWrite INFO     Writing new entries from DASS21_AS to active_data/DASS21_AS_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:01,708 export.safeKeep INFO     DASS21_AS data successfully backup as raw data.
2015-12-11 16:32:01,741 export.safeWrite INFO     Questionnaire DASS21_AS update finished - 21 new entries recoded successfully.
2015-12-11 16:32:01,742 export.safeRequest INFO     Trying to Request data for http://localhost:9000/api/export/DD_FU ......
2015-12-11 16:32:01,743 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): localhost
2015-12-11 16:32:01,776 export.safeRequest INFO     Data request successfully, see below for request detail:
http://localhost:9000/api/export/DD_FU
Issues: None
2015-12-11 16:32:01,776 export.safeExport INFO     Questionnaire DD_FU updated - 5 new entries received.
2015-12-11 16:32:01,776 export.safeWrite INFO     Writing new entries from DD_FU to active_data/DD_FU_Dec_11_2015.csv: writing in progress......
2015-12-11 16:32:01,778 export.safeKeep INFO     DD_FU data successfully backup as raw data.
2015-12-11 16:32:01,791 export.safeWrite INFO     Questionnaire DD_FU update finished - 5 new entries recoded successfully.
2015-12-11 16:32:01,791 export.safeExport INFO     Database update finished: 19 questionnaires' data updated.
